name: kdrive   #프로젝트 이름
description: A Naver Map scraper application  #프로젝트 설명

version: 1.0.0+1  #버전

environment:
  sdk: '>=3.2.5 <4.0.0'  #sdk 버전

# 라이브러리 목록`↓
dependencies:  
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  url_launcher: ^6.3.0
  get: ^4.6.5
  geolocator: ^10.1.0
  dio: ^5.6.0
  latlong2: ^0.9.1
  supabase_flutter: ^2.8.4
  video_player: ^2.8.1
  easy_localization: ^3.0.7+1
  flutter_inappwebview: ^6.1.5
  cached_network_image: ^3.3.1
  webview_flutter: ^4.8.0
  shimmer: ^3.0.0
  path_provider: ^2.1.2
  buttons_tabbar: ^1.3.6
  permission_handler: ^11.3.1  
  http: ^1.1.0
  html: ^0.15.4
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.0.0

# 개발 라이브러리 목록`↓ 배포할때는 필요없음
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

# flutter_launcher_icons 설정값 변경 후 컴파일 명령어 입력
# 아래는 컴파일 명령
# flutter pub run flutter_launcher_icons:main  ///로고 이미지 수정후 이부분을 복사해서 터미널에 붙여넣기
flutter_icons:
  image_path: "assets/launcher/mainlogo3.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/launcher/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
